---
title: "Sampler"
author: "Rihui Ou"
date: "4/1/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(readxl)
```

## Reading in Data

We read in the MWM data and connectome matrices:
```{r cars}
mwm<-read.csv("data/MWM.csv")
mwmlong<-read.csv("data/MWMlong.csv")
chasssy<-read_excel("data/CHASSSYMM3AtlasLegends.xlsx")
```


```{r}
filePaths <- list.files("data/Connectomes",
                        "\\.csv$", full.names = TRUE)
connectome_matlist <- lapply(filePaths,function(x) read.csv(x,header=FALSE) %>% as.matrix())

network <- connectome_matlist[[1]]
network2 <- connectome_matlist[[2]]
```

Binarizing Matrix Function:
```{r}
# takes matrix (matr) and binarizes each element 
# based on a threshold (strict less than)

binarize_matrix <- function(matr, threshold) {
  
  for (i in 1:length(matr)) {
    matr[[i]] <- ifelse(matr[[i]] < threshold, 0, 1)
  }
  
  return(matr)
}

```
Normalize
```{r}
normalize <- function(x){ 
  return((x-min(x))/(max(x)-min(x)))}
```

Difference in Networks (binarized matrices)
```{r}
# returns vector of number of edge deletions and additions needed for 
# binarized matr_1 to become binarized matr_2

network_diffs <- function(matr_1,matr_2,threshold) {
  
  # frequency matrix of -1,0,1 resulting from difference of bin. matrices
  diff_freq_matr <- (binarize_matrix(matr_2,threshold) - 
    binarize_matrix(matr_1,threshold)) %>% 
    table() %>%
    as.matrix()
  # Avoid NAs
  if(is.na(diff_freq_matr[3]))
    diff_freq_matr[3]=0
  
  return(diff_freq_matr[c(1,3)])
}
```

```{r}
network_diffs <- function(matr_1,matr_2,threshold) {
  
  # frequency matrix of -1,0,1 resulting from difference of bin. matrices
  diff_freq_matr <- binarize_matrix(matr_2,threshold) - 
    binarize_matrix(matr_1,threshold)
  add=sum(diff_freq_matr==1)
  del=sum(diff_freq_matr==-1)
  return(c(del,add))
}
```

Remove Subdivision 8 from the dataset
```{r}
indices=(chasssy$Subdivisions_7!="8_CSF")
indices=indices[-length(indices)]
for (i in 1:length(connectome_matlist)) {
  connectome_matlist[[i]] <- connectome_matlist[[i]][indices,indices]
}
```

Indexing Matrices by Runno
```{r}

# create list of identifiers corresponding to list of connectomes
regexp <- "N[[:digit:]]{5}"
matrix_labels <- lapply(filePaths,function(x) str_extract(x,regexp)) %>% unlist()

# takes vector of runnos (string format) and finds corresponding matrices
# returns vector of matrices if they exist, otherwise returns empty matrix

find_connects <- function(runnos) {
  
  idxs <- which(matrix_labels %in% runnos)
  
  if (length(idxs) == 0) {
    print("No matches")
    return(matrix())
  }
  
  return(connectome_matlist[idxs])
}

```


Sampler Function
```{r}

sampler <- function(iter, pis, B0, B1, data){
#Iteration and Initialization of Value
R=dim(B0)[1]
n= length(data)
Cs=rep(0,n)
Psi=matrix(0.5,2,2)
Psi_save = matrix(0,iter,4)

for(t in 1:iter){
  # draw C
  for (i in 1:n){
     #Assign membership to the cluster around B1 or B0 based on pis
    Cs[i] = sample(x =  c(1,0), size = 1, prob= c(pis[i], 1-pis[i]))
  }
  # Update Psi
  add_B0=0
  del_B0=0
  add_B1=0
  del_B1=0
  
  #For each network, if the network has been grouped around B0, then compute the additions and subtractions needed to get from B_i to B0
  #if the network has been grouped around B1, then compute the additions and subtractions needed to get from B_i to B1
  for (i in 1:n){
    if (Cs[i]==0){
      #deletions from B_i to B0
      del_B0=del_B0+del_B0_diff[i]
      #additions form B_i to B0
      add_B0=add_B0+add_B0_diff[i]
    }
    else{
      #deletions from B_i to B1
      del_B1=del_B1+del_B1_diff[i]
      #additions from B_i to B1
      add_B1=add_B1+add_B1_diff[i]
    }
  }
  # Update and sample phi_00 variable - probability of having to delete an edge to get to B0
  Psi[1,1]=rbeta(1,del_B0+1,1 + R^2*n - del_B0)
  
  #Update and sample phi_01 variable - probability of having to add an edge to get to B0
  Psi[1,2]=rbeta(1,add_B0+1,1 + R^2*n - add_B0)
  
  #Update and sample phi_10 variable - probability of having to delete an edge to get to B1 
  Psi[2,1]=rbeta(1,del_B1+1,1 + R^2*n - del_B1)
  
    #Update and sample phi_11 variable - probability of having to add an edge to get to B1
  Psi[2,2]=rbeta(1,add_B1+1,1 + R^2*n - add_B1)
  
  #save the Psi parameters
  Psi_save[t,] = c(Psi[1,1], Psi[1,2], Psi[2,1], Psi[2,2])
}

names <- c("phi_00", "phi_01", "phi_10",  "phi_11")
colnames(Psi_save)<- names
return(data.frame(Psi_save))
}
```

Choose response variables
```{r}
choose_res=function(mwmlong,matrix_labels,string){
  #Choose the average speed of  every mouse
  #String is the desired variable to choose
  result=rep(0,length(matrix_labels))
  i=1
  for (label in matrix_labels) {
    result[i]=mwmlong %>% 
    filter(grepl(label,runno,fixed = TRUE)) %>% 
    select(string) %>% 
    unlist() %>% 
    mean(na.rm=TRUE)
    i=i+1
  }
  return(result)
}
#Choose avg.sw.speed as a response and normalize
avg.sw.speed=choose_res(mwmlong = mwmlong, matrix_labels = matrix_labels, "Average.SW.Speed") %>% 
           normalize()

    

```

Try a 30 by 30 submatrix---much faster
```{r}
B0=connectome_matlist[[which.min(avg.sw.speed)]]
B1=connectome_matlist[[which.max(avg.sw.speed)]]
pis=avg.sw.speed
```

Compute the addition/ deletion needed 
```{r}
data=connectome_matlist
add_B0_diff=rep(0,length(connectome_matlist))
del_B0_diff=rep(0,length(connectome_matlist))
add_B1_diff=rep(0,length(connectome_matlist))
del_B1_diff=rep(0,length(connectome_matlist))

for(i in 1:length(connectome_matlist)){
      #deletions from B_i to B0
      del_B0_diff[i]=network_diffs(data[[i]],B0,0.5)[1]
      #additions form B_i to B0
      add_B0_diff[i]=network_diffs(data[[i]],B0,0.5)[2]
      #deletions from B_i to B1
      del_B1_diff[i]=network_diffs(data[[i]],B1,0.5)[1]
      #additions from B_i to B1
      add_B1_diff[i]=network_diffs(data[[i]],B1,0.5)[2]
}
  
```
Do sampling
```{r}
sampler(iter=3000,pis=avg.sw.speed,B0,B1,data=data)
```
